In [ ]:
!pip install -q python-dotenv
!pip install -q gradio
!pip install -q unstructured
!pip install -q openpyxl
!pip install -q tiktoken
!pip install -q chromadb
!pip install -q sentence-transformers
!pip install -q --upgrade langchain
!pip install -q -U langchain-chroma
!pip install -q -U langchain-google-vertexai
!pip install -q -U langchain-community
!pip install -q -U langchain langchain-huggingface
!pip install -q sqlalchemy
!pip install -q pymysql
!pip install -q openai mysql-connector-python

In [133]:
import os
import glob
import json
import chromadb
import mysql.connector
import openai
import gradio as gr
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import google.generativeai as genai
from dotenv import load_dotenv
from openai import OpenAI
from chromadb import chromadb
from sklearn.manifold import TSNE
from datetime import datetime
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, insert, Float, DateTime, inspect
#from google.colab import userdata

In [2]:
# imports for langchain

from langchain.document_loaders import DirectoryLoader, TextLoader, UnstructuredExcelLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.schema import Document
from langchain.embeddings import OpenAIEmbeddings, SentenceTransformerEmbeddings, HuggingFaceEmbeddings 
from langchain.vectorstores import Chroma
from langchain.chat_models import ChatOpenAI
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from langchain.prompts import PromptTemplate
from langchain_chroma import Chroma
from langchain_google_vertexai import ChatVertexAI #Import ChatVertexAI from langchain_google_vertexai
from pydantic import BaseModel

from chromadb import Client, Settings

In [166]:
# Load environment variables in a file called .env
load_dotenv()
os.environ['GOOGLE_API_KEY'] = os.getenv('GOOGLE_API_KEY', 'your-key-if-not-using-env')
os.environ['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY', 'your-key-if-not-using-env')
os.environ['MYSQL_KEYPW'] = os.getenv('MYSQL_KEYPW', 'your-key-if-not-using-env')

In [167]:
genai.configure(api_key=os.environ['GOOGLE_API_KEY'])
Gemini_model = genai.GenerativeModel("gemini-1.5-flash")
MODEL = "gemini-1.5-flash" 
#Testing Gemini AI
#response = model.generate_content("Explain how AI works")
#print(response.text)

In [168]:
# price is a factor for our company, so we're going to use a low cost model
db_name = "vector_db"

In [169]:
# Knowledge base is in /RAG_ImEx/Data
#knowledge_base_path = "Data/*"  
# Knowledge base is in /RAG_ImEx/Data_test
knowledge_base_path = "Data_test/*"

In [170]:
columns_to_remove = [
    'MA HQ', 'MA HAI QUAN', 'MA CHI CUC',
    'TEN HAI QUAN', 'SO DT', 'DIA DIEM CHO THONG QUAN',
    'DIA DIEM CHO THONG QUAN', 'DIA DIEM NHAN HANG',
    'DIA DIEM DO HANG', 'DIA DIEM XEP HANG', 'P.TIEN V.CHUYEN', 'TRI GIA',
    'NUOC NK','LOAI HINH'
]
address_cols = ['dia chi 1', 'dia chi 2', 'dia chi 3', 'dia chi 4']

header_translations = {
    "MA LH": "Import_Code", 
    "NHA NHAP KHAU" : "Importer_Name",
    "DIA CHI" : "Importer_Address",
    "nha xuat khau" : "Exporter_Name",
    "DIA CHI XK" : " Exporter_Address",
    "DON VI DOI TAC":"Partner_Company", 
    "DIA CHI DON VI DOI TAC" : "Partner_Address",
    "DK TT": "Payment_term",
    "DK GH": "Incoterms",
    "TI GIA": "Exchange_Rate",
    "NGAY" : "Date",
    "MA HANG" : "HSCODE",
    "TEN HANG": "Product_Info", 
    "LUONG": "Quantity",
    "DVT" : "Unit",
    "DON GIA" : "Unit_Price",
    "MA NT": "Payment_Currency",
    "THUE XNK" : "Import_Tax",
    "MA DOANH NGHIEP" : "Tax_ID",
}

In [171]:
def combine_excel_files(folder_path, excel_type, columns_to_remove, address_cols, header_translations):
    # Create an empty DataFrame to hold combined data
    combined_df = pd.DataFrame()
    
    # Use glob to find all Excel files in the specified folder that match the pattern
    excel_files = glob.glob(os.path.join(folder_path, excel_type))
    
    # Print found files for debugging
    print(f"Found files: {excel_files}")
    
    for file in excel_files:
        # Load each Excel file into a DataFrame
        df = pd.read_excel(file)
        
        # Convert all column names to lowercase
        df.columns = df.columns.str.lower()
        
        # Print column names for debugging
        #print(f"Columns in {file}: {df.columns.tolist()}")
        
        # Remove specified columns (in lowercase)
        columns_to_remove_lower = [col.lower() for col in columns_to_remove]
        df.drop(columns=columns_to_remove_lower, inplace=True, errors='ignore')
        
        # Check if address columns exist before combining them (in lowercase)
        existing_address_cols = [col for col in address_cols if col.lower() in df.columns]
        
        if existing_address_cols:
            # Combine address columns into a single column
            df['dia chi don vi doi tac'] = df[existing_address_cols].fillna('').agg(' '.join, axis=1)
            # Remove the original address columns after combining
            df.drop(columns=existing_address_cols, inplace=True, errors='ignore')
        else:
            print(f"No address columns found in {file}. Skipping combination.")
        
        # Rename headers according to the provided translations (keys should also be in lowercase)
        header_translations_lower = {k.lower(): v for k, v in header_translations.items()}
        df.rename(columns=header_translations_lower, inplace=True)

        # Clean up column names (remove trailing spaces, etc.)
        df.columns = df.columns.str.strip()  # Remove leading/trailing spaces
        df.columns = df.columns.str.replace(' ', '_')  # Replace spaces with underscores (optional)
        df.columns = df.columns.str.replace('[^A-Za-z0-9_]+', '', regex=True) # Remove special characters (optional)
        df.columns = df.columns.str.lower() # Convert to lowercase (optional, but recommended)

        
        # Append the processed DataFrame to the combined DataFrame
        combined_df = pd.concat([combined_df, df], ignore_index=True)

    # Print final combined DataFrame shape and contents for debugging
    #print(f"Final combined DataFrame shape: {combined_df.shape}")
    #print(combined_df.head())  # Display first few rows
    
    return combined_df

In [172]:
combined_df_NK = combine_excel_files(knowledge_base_path,'72NK*.xlsx', columns_to_remove, address_cols, header_translations)
combined_df_XK = combine_excel_files(knowledge_base_path,'72XK*.xlsx', columns_to_remove, address_cols, header_translations)

Found files: ['Data_test\\Raw Data\\72NK.T1.2024test.xlsx', 'Data_test\\Raw Data\\72NK.T3.2024test.xlsx']
Found files: ['Data_test\\Raw Data\\72XK.T6.2024test.xlsx', 'Data_test\\Raw Data\\72XK.T8.2021test.xlsx']

In [123]:
#print(combined_df_XK.head())
#print(combined_df_NK.head())

In [173]:
def insert_dataframe_to_sql(df, table_name, db_url, if_exists='fail'):
    """
    Inserts a DataFrame into a SQL database table.

    Parameters:
    - df: The DataFrame to insert.
    - table_name: The name of the table in the database.
    - db_url: The database connection URL.
    - if_exists: What to do if the table already exists. Options are 'fail', 'replace', 'append'.
    """
    # Create a database engine
    engine = create_engine(db_url)
    
    # Insert the DataFrame into the SQL table
    df.to_sql(name=table_name, con=engine, if_exists=if_exists, index=False)

# Example usage
# Define your database URL (replace with your actual credentials)
db_url = "mysql+pymysql://root:"+Mysqlkey+"@localhost:3306/my_database"

# Assuming combine_df is your DataFrame that you want to insert
insert_dataframe_to_sql(combined_df_NK, 'combined_table_nk', db_url, if_exists='replace')
insert_dataframe_to_sql(combined_df_XK, 'combined_table_xk', db_url, if_exists='replace')

In [178]:
# Replace with your OpenAI API key
openai.api_key = os.environ['OPENAI_API_KEY']

# Replace with your MySQL credentials
db_host = "localhost"
db_user = "root"
db_password = os.environ['MYSQL_KEYPW']
db_name = "my_database"

def execute_sql_from_user_query(user_query):
    try:
        # 1. Translate user query to SQL using OpenAI Chat Completion
        messages = [
            {"role": "system", "content": """
            Translate following user query into valid SQL command for MySQL, 
            Data for importing from tables named 'combined_table_nk'
            Data for exporting from tables named 'combined_table_xk'
            Be careful to generate efficient SQL, 
            for example, avoid `SELECT *` unless absolutely necessary.  
            If the user asks about specific columns, include them in the select statement. 
            If the user does not mention columns, and asks to see data, 
            select a reasonable number of important columns. 
            Just send out SQL code, no further comment or explain
            """},
            {"role": "user", "content": user_query},
        ]

        response = openai.chat.completions.create(  # Correct way to call Chat Completion
            model="gpt-3.5-turbo",  # Or gpt-4 if you have access
            messages=messages,
            max_tokens=200,
            temperature=0.0,
        )

        sql_command = response.choices[0].message.content.strip()

        print(f"Generated SQL: {sql_command}")

        # 2. Connect to MySQL (same as before)
        mydb = mysql.connector.connect(
            host=db_host,
            user=db_user,
            password=db_password,
            database=db_name
        )

        mycursor = mydb.cursor()

        # 3. Execute the SQL command (same as before)
        mycursor.execute(sql_command)

        # 4. Fetch the results (same as before)
        results = mycursor.fetchall()

        # 5. Convert results to Pandas DataFrame (same as before)
        column_names = [description[0] for description in mycursor.description]
        df = pd.DataFrame(results, columns=column_names)

        # 6. Close the connection (same as before)
        mydb.close()

        return df

    except mysql.connector.Error as err:
        return f"MySQL Error: {err}"
    except openai.APIError as err:  # Corrected OpenAI error handling!
        return f"OpenAI API Error: {err}"
    except Exception as err:
        return f"An error occurred: {err}"

In [179]:
# Usage
user_query = input("Enter your query: ")
result = execute_sql_from_user_query(user_query)

if isinstance(result, pd.DataFrame):
    print(result)
elif isinstance(result, str):  # Error message
    print(result)

Enter your query:  show export data

Generated SQL: SELECT * FROM combined_table_xk;
   import_code      tax_id                                      exporter_name  \
0          B11  1101982682              CôNG TY TNHH Cơ KHí XâY DựNG BảO DũNG
1          B11   302602610                     Công Ty TNHH Meinan (Việt Nam)
2          B11   302602610                     Công Ty TNHH Meinan (Việt Nam)
3          B11   302602610                     Công Ty TNHH Meinan (Việt Nam)
4          E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
5          E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
6          E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
7          E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
8          E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
9          E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
10         E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
11         E52  3401196669                         CôNG TY TNHH VINA SAPPHIRE
12         G61   100108663                              Tổng Công Ty Thành An
13         G61   100108663                              Tổng Công Ty Thành An
14         G61   100108663                              Tổng Công Ty Thành An
15         G61   100108663                              Tổng Công Ty Thành An
16         G61   100108663                              Tổng Công Ty Thành An
17         G61   100108663                              Tổng Công Ty Thành An
18         G61   100108663                              Tổng Công Ty Thành An
19        None   800740412  Công ty cổ phần luyện kim Tân Nguyên Hải Dương...
20        None  3700483421                       CôNG TY TNHH TAKAKO VIệT NAM
21        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam
22        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam
23        None   201905270                   CôNG TY TNHH Cơ KHí EBA VIệT NAM
24        None  2500503799                              Công ty TNHH UJU VINA
25        None  2500503799                              Công ty TNHH UJU VINA
26        None  2500503799                              Công ty TNHH UJU VINA
27        None   801224675                              CôNG TY TNHH LMS VINA
28        None  2500282740                            CôNG TY TNHH JAHWA VINA
29        None  3700483421                       CôNG TY TNHH TAKAKO VIệT NAM
30        None  3700483421                       CôNG TY TNHH TAKAKO VIệT NAM
31        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam
32        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam
33        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam
34        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam
35        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam
36        None   201934514        CôNG TY TNHH ĐIệN MáY ĐạI DươNG (HảI PHòNG)
37        None  2300852009              Công ty TNHH SAMSUNG DISPLAY Việt Nam

                                     exporter_address  \
0   289 Ấp Nhơn Hòa 2, Xã Đức Hòa Thượng, Huyện Đứ...
1   Lô 67, đường số 1, KCX Linh Trung II, P. Bình ...
2   Lô 67, đường số 1, KCX Linh Trung II, P. Bình ...
3   Lô 67, đường số 1, KCX Linh Trung II, P. Bình ...
4   Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
5   Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
6   Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
7   Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
8   Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
9   Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
10  Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
11  Lô A3.1 Cụm công nghiệp Đông Hà, Xã Đông Hà, H...
12  141 Hồ Đắc Di, phường Nam Đồng, quận Đống Đa, ...
13  141 Hồ Đắc Di, phường Nam Đồng, quận Đống Đa, ...
14  141 Hồ Đắc Di, phường Nam Đồng, quận Đống Đa, ...
15  141 Hồ Đắc Di, phường Nam Đồng, quận Đống Đa, ...
16  141 Hồ Đắc Di, phường Nam Đồng, quận Đống Đa, ...
17  141 Hồ Đắc Di, phường Nam Đồng, quận Đống Đa, ...
18  141 Hồ Đắc Di, phường Nam Đồng, quận Đống Đa, ...
19     Phường  Phú Thứ Thị xã Kinh Môn tỉnh Hải Dương
20  27 Đại Lộ Độc Lập, KCN VSIP, Thuận An, Bình Dương
21  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...
22  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...
23  Số 1171 km 8 Quốc lộ 5 - Phường Quán Toan - Qu...
24  SÓ 55, LÔ CN 12, KCN KHAI QUANG, VĨNH YÊN, VĨN...
25  SÓ 55, LÔ CN 12, KCN KHAI QUANG, VĨNH YÊN, VĨN...
26  SÓ 55, LÔ CN 12, KCN KHAI QUANG, VĨNH YÊN, VĨN...
27  Lô đất XN3-1E1,XN3-1G, XN3-1F KCN ĐẠI AN MỞ RỘ...
28  Lô CN10, KCN Khai Quang, P Khai Quang, TP Vĩnh...
29  27 Đại Lộ Độc Lập, KCN VSIP, Thuận An, Bình Dương
30  27 Đại Lộ Độc Lập, KCN VSIP, Thuận An, Bình Dương
31  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...
32  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...
33  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...
34  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...
35  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...
36  Địa chỉ: Nhà xưởng số 27,  lô đất CN8, KCN An ...
37  KCN Yên Phong, Xã Yên Trung, Huyện Yên Phong, ...

                                      partner_company incoterms  \
0                   YUSHENG SHIJI ENGINEERING CO.,LTD       DAP
1                                 CTY TNHH MTV CO BAN       EXW
2                                 CTY TNHH MTV CO BAN       EXW
3                                 CTY TNHH MTV CO BAN       EXW
4                                 SD WORKERS CO., LTD       CIF
5                                 SD WORKERS CO., LTD       CIF
6                                 SD WORKERS CO., LTD       CIF
7                                 SD WORKERS CO., LTD       CIF
8                                 SD WORKERS CO., LTD       CIF
9                                 SD WORKERS CO., LTD       CIF
10                                SD WORKERS CO., LTD       CIF
11                                SD WORKERS CO., LTD       CIF
12  CONSTRUCTION SITE COMMAND BOARD COMMITTEE COOP...       DAP
13  CONSTRUCTION SITE COMMAND BOARD COMMITTEE COOP...       DAP
14  CONSTRUCTION SITE COMMAND BOARD COMMITTEE COOP...       DAP
15  CONSTRUCTION SITE COMMAND BOARD COMMITTEE COOP...       DAP
16  CONSTRUCTION SITE COMMAND BOARD COMMITTEE COOP...       DAP
17  CONSTRUCTION SITE COMMAND BOARD COMMITTEE COOP...       DAP
18  CONSTRUCTION SITE COMMAND BOARD COMMITTEE COOP...       DAP
19                           DOUWA ENTERPRISE LIMITED       CFR
20  CONG TY TNHH SAN XUAT THUONG MAI DICH VU MOI T...       DAP
21           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW
22           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW
23                       CONG TY TNHH CHE TAO MAY EBA       DAP
24                            UJU ELECTRONICS CO.,LTD       DAP
25             CONG TY CO PHAN MOI TRUONG THUAN THANH       DAP
26                            UJU ELECTRONICS CO.,LTD       DAP
27                           CONG TY TNHH HOANG THANH       DAP
28                            CONG TY TNHH PHUC AN VP       DAP
29  CONG TY TNHH SAN XUAT THUONG MAI DICH VU MOI T...       DAP
30  CONG TY TNHH SAN XUAT THUONG MAI DICH VU MOI T...       DAP
31           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW
32           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW
33           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW
34           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW
35           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW
36    CONG TY TNHH XD & TM VAN TAI GIA HUNG HAI PHONG       EXW
37           CONG TY CO PHAN MOI TRUONG VIET XUAN MOI       EXW

   payment_currency  exchange_rate                 date    hscode  \
0               USD        25250.0  2024-06-01 00:00:00  72287010
1               VND            NaN  2024-06-01 00:00:00  72044100
2               VND            NaN  2024-06-01 00:00:00  72042100
3               VND            NaN  2024-06-01 00:00:00  72042100
4               USD        25250.0  2024-06-01 00:00:00  72199000
5               USD        25250.0  2024-06-01 00:00:00  72199000
6               USD        25250.0  2024-06-01 00:00:00  72199000
7               USD        25250.0  2024-06-01 00:00:00  72199000
8               USD        25250.0  2024-06-01 00:00:00  72199000
9               USD        25250.0  2024-06-01 00:00:00  72199000
10              USD        25250.0  2024-06-01 00:00:00  72199000
11              USD        25250.0  2024-06-01 00:00:00  72199000
12              VND            NaN  2024-06-01 00:00:00  72171029
13              VND            NaN  2024-06-01 00:00:00  72159091
14              VND            NaN  2024-06-01 00:00:00  72159091
15              VND            NaN  2024-06-01 00:00:00  72159091
16              VND            NaN  2024-06-01 00:00:00  72159091
17              VND            NaN  2024-06-01 00:00:00  72159091
18              VND            NaN  2024-06-01 00:00:00  72159091
19              USD        22920.0           01/08/2021  72021900
20              VND            1.0           01/08/2021  72041000
21              VND            1.0           01/08/2021  72042100
22              VND            1.0           01/08/2021  72042100
23              VND            1.0           01/08/2021  72042900
24              USD        22920.0           01/08/2021  72044100
25              VND            1.0           01/08/2021  72044100
26              USD        22920.0           01/08/2021  72044100
27              VND            1.0           01/08/2021  72044100
28              VND            1.0           01/08/2021  72044100
29              VND            1.0           01/08/2021  72044100
30              VND            1.0           01/08/2021  72044100
31              VND            1.0           01/08/2021  72044900
32              VND            1.0           01/08/2021  72044900
33              VND            1.0           01/08/2021  72044900
34              VND            1.0           01/08/2021  72044900
35              VND            1.0           01/08/2021  72044900
36              VND            1.0           01/08/2021  72044900
37              VND            1.0           01/08/2021  72044900

                                         product_info  quantity     unit  \
0   Thép hình chữ V - STAY, không hợp kim, chưa gi...    941.02      KGM
1        Phế liệu sắt phoi thừa (steel remnants) #&VN   1440.00      KGM
2        Phế liệu inox phoi thừa ( inox remnants)#&VN   2418.00      KGM
3        Phế liệu inox ép viên ( inox chip block)#&VN  20575.00      KGM
4   304-PVD-HL-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   2508.00      KGM
5   304-PVD-HL-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   6022.00      KGM
6   304-PVD-HL-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   2014.00      KGM
7   304-PVD-HL-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   3042.00      KGM
8   304-PVD-HL-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   1990.00      KGM
9   304-PVD-HL-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   2010.00      KGM
10  304-PVD-SM-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   1990.00      KGM
11  304-PVD-HL-1.2mm-V2#&Sản phẩm thép không gỉ dạ...   3002.00      KGM
12  Dây thép 1 ly từ thép không hợp kim có hàm lượ...    200.00      KGM
13  Thanh sắt tròn D10mm , thép không hợp kim ,có ...   2772.00      KGM
14  Thanh sắt tròn D12mm , thép không hợp kim ,có ...   1485.00      KGM
15  Thanh sắt tròn D14mm , thép không hợp kim ,có ...   3019.00      KGM
16  Thanh sắt tròn D16mm , thép không hợp kim ,có ...   6228.00      KGM
17  Thanh sắt tròn D18mm , thép không hợp kim ,có ...   6210.00      KGM
18  Thanh sắt tròn D20mm , thép không hợp kim ,có ...   3169.00      KGM
19  Hợp kim  ferro mangan hàm lượng Cacbon vừa Mn ...    200.00      Tấn
20  Phoi gang#&Phôi gang phế liệu (mảnh vụn và bột...   3390.00  Kilogam
21  Phế liệu thép không gỉ (SUS 201) (thu được từ ...   1380.00  Kilogam
22  Phế liệu thép không gỉ (SUS 304) (thu được từ ...   1020.00  Kilogam
23  .#&Phế liệu thép (dạng tấm, thanh) loại bỏ tro...  59396.00  Kilogam
24  -#&Phế liệu khung thép hợp kim không gỉ (Tỷ lệ...    435.50  Kilogam
25  -#&Phế liệu khung thép hợp kim không gỉ (Tỷ lệ...    232.00  Kilogam
26  -#&Phế liệu khung thép hợp kim không gỉ (Tỷ lệ...   3259.00  Kilogam
27  ChipSUS-20#&Phế liệu thép không gỉ dạng phoi, ...  15022.00  Kilogam
28  -#&.#&Phế liệu sắt (Phế liệu dạng  vụn tấm bị ...     21.00  Kilogam
29  Phoi thep#&Phoi thép tiện phế liệu (sợi xoắn v...   3890.00  Kilogam
30  Phoi thep#&Phoi thép tiện phế liệu (sợi xoắn v...   3469.00  Kilogam
31  Phế liệu sắt loại 4 (thu được từ quá trình sản...   1670.00  Kilogam
32  Phế liệu sắt loại 4 (thu được từ quá trình sản...  26550.00  Kilogam
33  Phế liệu sắt loại 2 (thu được từ quá trình sản...   6060.00  Kilogam
34  Phế liệu sắt loại 4 (thu được từ quá trình sản...   1300.00  Kilogam
35  Phế liệu sắt loại 4 (thu được từ quá trình sản...  28500.00  Kilogam
36  Thép phế liệu: thép dạng mảnh vụn, bavia, tầu ...  98770.00  Kilogam
37  Phế liệu sắt loại 1 (thu được từ quá trình sản...   5810.00  Kilogam

      unit_price                                    partner_address
0       0.930001        TAISENG 4- SPECIAL ECONOMIC ZONE   CAMBODIA
1    4600.000000  6A NGO CHI QUOC KP2, P BINH CHIEU TP. THU DUC ...
2   16500.000000  6A NGO CHI QUOC KP2, P BINH CHIEU TP. THU DUC ...
3   14000.000000  6A NGO CHI QUOC KP2, P BINH CHIEU TP. THU DUC ...
4       2.920000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
5       2.910000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
6       2.940000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
7       2.930000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
8       3.020000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
9       3.090000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
10      3.390000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
11      3.040000  1ST FLOOR, 1502, NAMBUSUNHWAN-RO, GWANAK-GU, S...
12  56000.000000  NHAC NUA VILLAGE ,SAM PHAN DISTRICT   PHONGSAL...
13  14765.000000  NHAC NUA VILLAGE ,SAM PHAN DISTRICT   PHONGSAL...
14  14765.000000  NHAC NUA VILLAGE ,SAM PHAN DISTRICT   PHONGSAL...
15  14765.000000  NHAC NUA VILLAGE ,SAM PHAN DISTRICT   PHONGSAL...
16  14765.000000  NHAC NUA VILLAGE ,SAM PHAN DISTRICT   PHONGSAL...
17  14765.000000  NHAC NUA VILLAGE ,SAM PHAN DISTRICT   PHONGSAL...
18  14765.000000  NHAC NUA VILLAGE ,SAM PHAN DISTRICT   PHONGSAL...
19   1630.000000  FLAT/RM 903A, 9F CAPITAL CENTRE 151, GLOUCESTE...
20      0.179959  LO N1, DUONG N8, KCN NAM TAN UYEN, KHANH BINH,...
21      0.369793  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...
22      0.802967  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...
23      0.153623  LO N-1, N-2, N-3 KCN NOMURA, HAI PHONG, XA TAN...
24      0.290000  61, CHOROK-RO 532BEON-GIL, YANGGAM-MYEON, HWAS...
25      3.643067  THON NGOC KHAM, XA GIA DONG, HUYEN THUAN THANH...
26      1.100000  61, CHOROK-RO 532BEON-GIL, YANGGAM-MYEON, HWAS...
27      0.498925  THON CAM LY, XA AN LAM, HUYEN NAM SACH, TINH H...
28      0.307247  SO 38 DUONG NGUYEN DU, P KHAI QUANG, THANH PHO...
29      0.193126  LO N1, DUONG N8, KCN NAM TAN UYEN, KHANH BINH,...
30      0.193126  LO N1, DUONG N8, KCN NAM TAN UYEN, KHANH BINH,...
31      0.621384  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...
32      0.622657  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...
33      0.211342  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...
34      0.623360  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...
35      0.622043  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...
36      0.359917  TO DAN PHO VAN TRANG 1, THI TRAN TRUONG SON, H...
37      0.290568  XOM 2, XA MINH DUC, THI XA PHO YEN, TINH THAI ...

In [193]:
# Wrapping in a function - note that history isn't used, as the memory is in the conversation_chain
def chat(message, history=[]):  # Accept both message and history
    try:
        result = execute_sql_from_user_query(message)

        if isinstance(result, pd.DataFrame):
            # Best practice: Return a string representation of the DataFrame for Gradio
            return str(result)  # Or result.to_string() for more control
        elif isinstance(result, str):  # Error message
            return result
        else:  # Handle other potential return types
            return "Unexpected result type from SQL execution."

    except Exception as e:  # Catch and display exceptions
        return f"Error during SQL execution: {str(e)}"

In [194]:
# And in Gradio:

view = gr.ChatInterface(chat, type="messages").launch(inbrowser=False, share=True)

* Running on local URL:  http://127.0.0.1:7865
* Running on public URL: https://8c2940accf148de5fb.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Generated SQL: SHOW DATABASES;
Generated SQL: SHOW DATABASES;
Generated SQL: SELECT * FROM combined_table_nk;
Generated SQL: SELECT * FROM combined_table_nk;
Generated SQL: SELECT * FROM combined_table_nk;